### ISSUE TITLE
Why choose RawArray instead of Array?

### ISSUE THREAD

**Issue by CCGY** [bslatkin/ringbuffer#7]
It is greate work but I have one question:
The documentation mentioned that multiprocessing.Array is more is more atomic, and reading from the documentation, rawArray and Array seem to be the same, just Array is process safe. Could you explain a bit about why you are using rawArray?

PS: I am using Python3.5 & python3.6, and I am mainly interested in saving numpy ndarray (image) and timestamps in the ring buffer so I am creating a customized strcut and feed it into ringbuffer.

**Comment by bslatkin** [comment]
The accesses to the `RawArray` are protected via a readers/writer lock that's implemented with other primitives. So the data is still atomic and doesn't get corrupted, but the performance is much better than `Array` would be due to lower lock contention. See this part of the code:

https://github.com/bslatkin/ringbuffer/blob/898c893c1a6944a999919a69d1f9527cb2af096b/ringbuffer.py#L317
